build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:7.7.0
  amd64:   ghcr.io/hassio-addons/debian-base:7.7.0
  armv7:   ghcr.io/hassio-addons/debian-base:7.7.0
  armhf:   ghcr.io/hassio-addons/debian-base:7.7.0
  i386:    ghcr.io/hassio-addons/debian-base:7.7.0
codenotary:
  base_image: codenotary@pewi72.dev
  signer:     codenotary@pewi72.dev
