name: Tibber MQTT
version: "1.0.0"
slug: tibber-mqtt
description: "Publishes live Tibber data to MQTT with Home Assistant autodiscovery"
arch:
  - aarch64
  - armv7
  - armhf
  - amd64
  - i386
startup: services
boot: auto
options:
  token: ""
  home_id: ""
schema:
  token:
    type: string
    description: "Din Tibber API token"
  home_id:
    type: string
    description: "ID för ditt Tibber hem"
mqtt:
  server: core-mosquitto
  user: mqtt
  password: mqtt
webui: null
host_network: true
