#!/bin/bash

TOKEN=$TIBBER_TOKEN
HOME_ID=$HOME_ID
MQTT_HOST=$MQTT_HOST
MQTT_PORT=$MQTT_PORT
MQTT_USER=$MQTT_USER
MQTT_PASS=$MQTT_PASSWORD

python3 /app/tibber.py "$TOKEN" "$HOME_ID" "$MQTT_HOST" "$MQTT_PORT" "$MQTT_USER" "$MQTT_PASS"
