#!/bin/bash

TOKEN=$TIBBER_TOKEN
HOME_ID=$HOME_ID
MQTT_HOST=$MQTT_HOST
MQTT_PORT=$MQTT_PORT
MQTT_USER=$MQTT_USER
MQTT_PASS=$MQTT_PASSWORD

echo "[TIBBER MQTT DEBUG] Miljövariabler:"
echo "TOKEN=$TOKEN"
echo "HOME_ID=$HOME_ID"
echo "MQTT_HOST=$MQTT_HOST"
echo "MQTT_PORT=$MQTT_PORT"
echo "MQTT_USER=$MQTT_USER"

python3 /app/tibber.py "$TOKEN" "$HOME_ID" "$MQTT_HOST" "$MQTT_PORT" "$MQTT_USER" "$MQTT_PASS"
